export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const VK_USER = 'VK_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_TOKEN_FROM_DB = 'SET_TOKEN_FROM_DB';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const SET_ERROR_TOKEN = 'SET_ERROR_TOKEN';

// CONTENT
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS';
